import {
  Module,
  Testimonial,
  FAQItem,
  VaultResource,
  LessonComment,
  UserProfile,
  Enrollment,
  AdminTransaction,
  AdminStudent,
  AdminDiscountCode,
  AdminModule,
} from '@/types/index';

export const MOCK_ADMIN_TRANSACTIONS: AdminTransaction[] = [
  {
    id: 'tx-1001',
    date: '2026-08-24 14:18',
    studentName: 'Chidi Okonkwo',
    studentEmail: 'chidi.okonkwo@gmail.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'paid',
    reference: 'FLG-84920193',
  },
  {
    id: 'tx-1002',
    date: '2026-08-24 13:05',
    studentName: 'Amina Bello',
    studentEmail: 'amina.bello@kudabank.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 5000000,
    discountCode: 'FLAG50',
    status: 'paid',
    reference: 'FLG-91048201',
  },
  {
    id: 'tx-1003',
    date: '2026-08-24 11:42',
    studentName: 'Oluwaseun Adeyemi',
    studentEmail: 'seun.adeyemi@flutterwave.ng',
    product: 'recordings',
    productName: 'On-Demand Recordings Archive',
    amountKobo: 5000000,
    status: 'paid',
    reference: 'FLG-72819034',
  },
  {
    id: 'tx-1004',
    date: '2026-08-24 09:30',
    studentName: 'Emeka Nwosu',
    studentEmail: 'emeka.nwosu@gmail.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'paid',
    reference: 'FLG-61928341',
  },
  {
    id: 'tx-1005',
    date: '2026-08-23 21:15',
    studentName: 'Tunde Bakare',
    studentEmail: 'tunde.bakare@paystack.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 0,
    discountCode: 'ALUMNI-VIP2026',
    status: 'paid',
    reference: 'FLG-ALM-552019',
  },
  {
    id: 'tx-1006',
    date: '2026-08-23 18:40',
    studentName: 'Zainab Mohammed',
    studentEmail: 'zainab.m@interswitchng.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'pending',
    reference: 'FLG-48192039',
  },
  {
    id: 'tx-1007',
    date: '2026-08-23 15:10',
    studentName: 'Kayode Alabi',
    studentEmail: 'kayode.alabi@piggyvest.com',
    product: 'recordings',
    productName: 'On-Demand Recordings Archive',
    amountKobo: 5000000,
    status: 'paid',
    reference: 'FLG-39182049',
  },
  {
    id: 'tx-1008',
    date: '2026-08-23 11:22',
    studentName: 'Ifeanyi Okafor',
    studentEmail: 'ifeanyi.okafor@moniepoint.com',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'failed',
    reference: 'FLG-28192038',
  },
  {
    id: 'tx-1009',
    date: '2026-08-22 20:04',
    studentName: 'Ngozi Eze',
    studentEmail: 'ngozi.eze@hellosecur.io',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'paid',
    reference: 'FLG-19283019',
  },
  {
    id: 'tx-1010',
    date: '2026-08-22 16:30',
    studentName: 'Babatunde Fashola',
    studentEmail: 'b.fashola@cloudscale.ng',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'refunded',
    reference: 'FLG-09182938',
  },
  {
    id: 'tx-1011',
    date: '2026-08-22 12:15',
    studentName: 'Blessing Udoh',
    studentEmail: 'blessing.u@reliancehmo.com',
    product: 'recordings',
    productName: 'On-Demand Recordings Archive',
    amountKobo: 5000000,
    status: 'paid',
    reference: 'FLG-98210394',
  },
  {
    id: 'tx-1012',
    date: '2026-08-21 19:44',
    studentName: 'Femi Otedola Jr.',
    studentEmail: 'femi.jr@zenithbank.ng',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'paid',
    reference: 'FLG-87192039',
  },
  {
    id: 'tx-1013',
    date: '2026-08-21 14:02',
    studentName: 'Fatima Yusuf',
    studentEmail: 'fatima.yusuf@devmail.ng',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 5000000,
    discountCode: 'EARLY2026',
    status: 'paid',
    reference: 'FLG-76192038',
  },
  {
    id: 'tx-1014',
    date: '2026-08-20 10:18',
    studentName: 'Damilola Adeleke',
    studentEmail: 'dami.adeleke@opay.ng',
    product: 'recordings',
    productName: 'On-Demand Recordings Archive',
    amountKobo: 5000000,
    status: 'paid',
    reference: 'FLG-65182930',
  },
  {
    id: 'tx-1015',
    date: '2026-08-19 17:50',
    studentName: 'Victor Osimhen',
    studentEmail: 'victor.o@victorlabs.io',
    product: 'cohort',
    productName: 'Live Cohort 2 + Complete Archive',
    amountKobo: 10000000,
    status: 'paid',
    reference: 'FLG-54192837',
  },
];

export const MOCK_ADMIN_STUDENTS: AdminStudent[] = [
  {
    id: 'usr-4911',
    name: 'Chidi Okonkwo',
    email: 'chidi.okonkwo@gmail.com',
    enrollments: ['Live Cohort 2 + Complete Archive'],
    tier: 'cohort',
    progressPercent: 31,
    completedLessonsCount: 4,
    totalLessonsCount: 13,
    lastActive: '12 mins ago',
    joinedDate: '2026-02-18',
    isAlumni: false,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)', completedAt: '2026-02-19' },
      { lessonId: 'les-0-2', lessonTitle: 'Local Environment, Node.js & Cloud', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 45, isCompleted: true, lastPositionSeconds: 2700, lastPositionFormatted: '45:00 (100%)', completedAt: '2026-02-19' },
      { lessonId: 'les-1-1', lessonTitle: 'Fundamentals of AI', moduleNumber: 1, moduleTitle: 'AI Foundations', durationMinutes: 95, isCompleted: true, lastPositionSeconds: 5700, lastPositionFormatted: '95:00 (100%)', completedAt: '2026-02-20' },
      { lessonId: 'les-1-2', lessonTitle: 'Prompting & Content Generation', moduleNumber: 1, moduleTitle: 'AI Foundations', durationMinutes: 90, isCompleted: true, lastPositionSeconds: 5400, lastPositionFormatted: '90:00 (100%)', completedAt: '2026-02-21' },
      { lessonId: 'les-1-3', lessonTitle: 'Prompting Pt 2 — Structured Chains', moduleNumber: 1, moduleTitle: 'AI Foundations', durationMinutes: 110, isCompleted: false, lastPositionSeconds: 1200, lastPositionFormatted: '20:00 (18%)' },
      { lessonId: 'les-2-1', lessonTitle: 'Foundations of Automation & n8n', moduleNumber: 2, moduleTitle: 'n8n Workflows', durationMinutes: 95, isCompleted: false, lastPositionSeconds: 0, lastPositionFormatted: '0:00 (0%)' },
      { lessonId: 'les-2-2', lessonTitle: 'AI-Powered Email Response System', moduleNumber: 2, moduleTitle: 'n8n Workflows', durationMinutes: 120, isCompleted: false, lastPositionSeconds: 0, lastPositionFormatted: '0:00 (0%)' },
      { lessonId: 'les-3-1', lessonTitle: 'Deep Research Agent', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 105, isCompleted: false, lastPositionSeconds: 0, lastPositionFormatted: '0:00 (0%)' },
      { lessonId: 'les-3-2', lessonTitle: 'Calendar Management Agent Pt 2', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 115, isCompleted: false, lastPositionSeconds: 2712, lastPositionFormatted: '45:12 (39%)' },
    ],
  },
  {
    id: 'usr-4912',
    name: 'Amina Bello',
    email: 'amina.bello@kudabank.com',
    enrollments: ['Live Cohort 2 + Complete Archive', 'January 2026 Workshop'],
    tier: 'cohort',
    progressPercent: 92,
    completedLessonsCount: 12,
    totalLessonsCount: 13,
    lastActive: '45 mins ago',
    joinedDate: '2026-01-05',
    isAlumni: true,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)', completedAt: '2026-01-06' },
      { lessonId: 'les-1-1', lessonTitle: 'Fundamentals of AI', moduleNumber: 1, moduleTitle: 'AI Foundations', durationMinutes: 95, isCompleted: true, lastPositionSeconds: 5700, lastPositionFormatted: '95:00 (100%)', completedAt: '2026-01-08' },
      { lessonId: 'les-2-1', lessonTitle: 'Foundations of Automation & n8n', moduleNumber: 2, moduleTitle: 'n8n Workflows', durationMinutes: 95, isCompleted: true, lastPositionSeconds: 5700, lastPositionFormatted: '95:00 (100%)', completedAt: '2026-01-12' },
      { lessonId: 'les-3-1', lessonTitle: 'Deep Research Agent', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 105, isCompleted: true, lastPositionSeconds: 6300, lastPositionFormatted: '105:00 (100%)', completedAt: '2026-01-20' },
      { lessonId: 'les-3-2', lessonTitle: 'Calendar Management Agent Pt 2', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 115, isCompleted: true, lastPositionSeconds: 6900, lastPositionFormatted: '115:00 (100%)', completedAt: '2026-02-15' },
    ],
  },
  {
    id: 'usr-4913',
    name: 'Oluwaseun Adeyemi',
    email: 'seun.adeyemi@flutterwave.ng',
    enrollments: ['On-Demand Recordings Archive'],
    tier: 'recordings',
    progressPercent: 54,
    completedLessonsCount: 7,
    totalLessonsCount: 13,
    lastActive: '3 hours ago',
    joinedDate: '2026-02-10',
    isAlumni: false,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)' },
      { lessonId: 'les-1-1', lessonTitle: 'Fundamentals of AI', moduleNumber: 1, moduleTitle: 'AI Foundations', durationMinutes: 95, isCompleted: true, lastPositionSeconds: 5700, lastPositionFormatted: '95:00 (100%)' },
      { lessonId: 'les-2-1', lessonTitle: 'Foundations of Automation & n8n', moduleNumber: 2, moduleTitle: 'n8n Workflows', durationMinutes: 95, isCompleted: true, lastPositionSeconds: 5700, lastPositionFormatted: '95:00 (100%)' },
    ],
  },
  {
    id: 'usr-4914',
    name: 'Emeka Nwosu',
    email: 'emeka.nwosu@gmail.com',
    enrollments: ['Live Cohort 2 + Complete Archive'],
    tier: 'cohort',
    progressPercent: 69,
    completedLessonsCount: 9,
    totalLessonsCount: 13,
    lastActive: '1 hour ago',
    joinedDate: '2026-02-12',
    isAlumni: false,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)' },
      { lessonId: 'les-3-2', lessonTitle: 'Calendar Management Agent Pt 2', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 115, isCompleted: true, lastPositionSeconds: 6900, lastPositionFormatted: '115:00 (100%)' },
    ],
  },
  {
    id: 'usr-4915',
    name: 'Tunde Bakare',
    email: 'tunde.bakare@paystack.com',
    enrollments: ['Live Cohort 2 + Complete Archive', 'January 2026 Workshop'],
    tier: 'cohort',
    progressPercent: 100,
    completedLessonsCount: 13,
    totalLessonsCount: 13,
    lastActive: '5 hours ago',
    joinedDate: '2026-01-02',
    isAlumni: true,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)' },
      { lessonId: 'les-4-1', lessonTitle: 'Production RAG Systems', moduleNumber: 4, moduleTitle: 'Enterprise RAG', durationMinutes: 110, isCompleted: true, lastPositionSeconds: 6600, lastPositionFormatted: '110:00 (100%)' },
      { lessonId: 'les-5-1', lessonTitle: 'Deploying & Scaling in Production', moduleNumber: 5, moduleTitle: 'Live Mentorship', durationMinutes: 120, isCompleted: true, lastPositionSeconds: 7200, lastPositionFormatted: '120:00 (100%)' },
    ],
  },
  {
    id: 'usr-4916',
    name: 'Zainab Mohammed',
    email: 'zainab.m@interswitchng.com',
    enrollments: ['Live Cohort 2 + Complete Archive'],
    tier: 'cohort',
    progressPercent: 0,
    completedLessonsCount: 0,
    totalLessonsCount: 13,
    lastActive: 'Yesterday',
    joinedDate: '2026-02-23',
    isAlumni: false,
    lessonProgressList: [],
  },
  {
    id: 'usr-4917',
    name: 'Kayode Alabi',
    email: 'kayode.alabi@piggyvest.com',
    enrollments: ['On-Demand Recordings Archive'],
    tier: 'recordings',
    progressPercent: 23,
    completedLessonsCount: 3,
    totalLessonsCount: 13,
    lastActive: '2 days ago',
    joinedDate: '2026-02-15',
    isAlumni: false,
    lessonProgressList: [
      { lessonId: 'les-0-1', lessonTitle: 'Platform Overview & Tool Stack', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 40, isCompleted: true, lastPositionSeconds: 2400, lastPositionFormatted: '40:00 (100%)' },
      { lessonId: 'les-0-2', lessonTitle: 'Local Environment, Node.js & Cloud', moduleNumber: 0, moduleTitle: 'Onboarding', durationMinutes: 45, isCompleted: true, lastPositionSeconds: 2700, lastPositionFormatted: '45:00 (100%)' },
    ],
  },
  {
    id: 'usr-4918',
    name: 'Fatima Yusuf',
    email: 'fatima.yusuf@devmail.ng',
    enrollments: ['Live Cohort 2 + Complete Archive', 'January 2026 Workshop'],
    tier: 'cohort',
    progressPercent: 85,
    completedLessonsCount: 11,
    totalLessonsCount: 13,
    lastActive: '4 hours ago',
    joinedDate: '2026-01-11',
    isAlumni: true,
    lessonProgressList: [
      { lessonId: 'les-3-2', lessonTitle: 'Calendar Management Agent Pt 2', moduleNumber: 3, moduleTitle: 'Autonomous Agents', durationMinutes: 115, isCompleted: true, lastPositionSeconds: 6900, lastPositionFormatted: '115:00 (100%)' },
    ],
  },
  {
    id: 'usr-4919',
    name: 'Victor Osimhen',
    email: 'victor.o@victorlabs.io',
    enrollments: ['Live Cohort 2 + Complete Archive'],
    tier: 'cohort',
    progressPercent: 46,
    completedLessonsCount: 6,
    totalLessonsCount: 13,
    lastActive: '1 day ago',
    joinedDate: '2026-02-19',
    isAlumni: false,
    lessonProgressList: [],
  },
  {
    id: 'usr-4920',
    name: 'Blessing Udoh',
    email: 'blessing.u@reliancehmo.com',
    enrollments: ['On-Demand Recordings Archive'],
    tier: 'recordings',
    progressPercent: 77,
    completedLessonsCount: 10,
    totalLessonsCount: 13,
    lastActive: '6 hours ago',
    joinedDate: '2026-02-05',
    isAlumni: false,
    lessonProgressList: [],
  },
];

export const MOCK_ADMIN_CODES: AdminDiscountCode[] = [
  {
    id: 'code-1',
    code: 'ALUMNI-2026-001',
    kind: 'alumni',
    valueDescription: '100% OFF (₦100,000)',
    discountPercent: 100,
    discountKobo: 10000000,
    appliesTo: 'cohort',
    redemptionsUsed: 1,
    maxRedemptions: 1,
    expiryDate: '2026-03-31',
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'code-2',
    code: 'ALUMNI-2026-002',
    kind: 'alumni',
    valueDescription: '100% OFF (₦100,000)',
    discountPercent: 100,
    discountKobo: 10000000,
    appliesTo: 'cohort',
    redemptionsUsed: 0,
    maxRedemptions: 1,
    expiryDate: '2026-03-31',
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'code-3',
    code: 'ALUMNI-2026-003',
    kind: 'alumni',
    valueDescription: '100% OFF (₦100,000)',
    discountPercent: 100,
    discountKobo: 10000000,
    appliesTo: 'cohort',
    redemptionsUsed: 1,
    maxRedemptions: 1,
    expiryDate: '2026-03-31',
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'code-4',
    code: 'FLAG50',
    kind: 'promo',
    valueDescription: '50% OFF (₦50,000)',
    discountPercent: 50,
    discountKobo: 5000000,
    appliesTo: 'all',
    redemptionsUsed: 84,
    maxRedemptions: 100,
    expiryDate: '2026-02-28',
    isActive: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'code-5',
    code: 'EARLY2026',
    kind: 'promo',
    valueDescription: '50% OFF (₦50,000)',
    discountPercent: 50,
    discountKobo: 5000000,
    appliesTo: 'cohort',
    redemptionsUsed: 50,
    maxRedemptions: 50,
    expiryDate: '2026-02-20',
    isActive: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'code-6',
    code: 'INVITE-LAGOS-TECH',
    kind: 'invite',
    valueDescription: '100% Free Access',
    discountPercent: 100,
    discountKobo: 10000000,
    appliesTo: 'cohort',
    redemptionsUsed: 12,
    maxRedemptions: 25,
    expiryDate: '2026-03-15',
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'code-7',
    code: 'TWITTER-SPECIAL-20',
    kind: 'promo',
    valueDescription: '20% OFF (₦20,000)',
    discountPercent: 20,
    discountKobo: 2000000,
    appliesTo: 'recordings',
    redemptionsUsed: 18,
    maxRedemptions: 100,
    expiryDate: '2026-03-10',
    isActive: true,
    createdAt: '2026-02-18',
  },
  {
    id: 'code-8',
    code: 'ALUMNI-VIP2026',
    kind: 'alumni',
    valueDescription: '100% OFF (₦100,000)',
    discountPercent: 100,
    discountKobo: 10000000,
    appliesTo: 'cohort',
    redemptionsUsed: 42,
    maxRedemptions: 50,
    expiryDate: '2026-04-30',
    isActive: true,
    createdAt: '2026-01-28',
  },
];

export const MOCK_MODULES: Module[] = [
  {
    id: 'mod-0',
    number: 0,
    title: 'Onboarding & Workspace Setup',
    lessonCount: 2,
    totalDurationMinutes: 85,
    description: 'Orientation, tools provisioning, development environments, and community protocols.',
    lessons: [
      {
        id: 'les-0-1',
        title: 'Platform Overview, Community Guidelines & Tool Stack',
        durationMinutes: 40,
        isFree: false,
        bunnyVideoId: 'f6b219a1-081b-411a-8c9e-2e4a81d11100',
        description: 'Introduction to our learning platform, Telegram workspace, API access keys, and project milestones.',
      },
      {
        id: 'les-0-2',
        title: 'Local Environment, Node.js, Python & Cloud Sandboxes',
        durationMinutes: 45,
        isFree: false,
        bunnyVideoId: 'f6b219a1-081b-411a-8c9e-2e4a81d11101',
        description: 'Setting up clean environments, secure token management, and containerized development tools.',
      },
    ],
  },
  {
    id: 'mod-1',
    number: 1,
    title: 'AI Foundations & Engineering Mindset',
    lessonCount: 3,
    totalDurationMinutes: 295,
    description: 'Deep dive into LLM mechanics, tokenization, context windows, and deterministic prompting techniques.',
    lessons: [
      {
        id: 'les-1-1',
        title: 'Fundamentals of AI',
        durationMinutes: 95,
        isFree: true,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b01',
        description: 'How modern transformer models think, embeddings, temperature, latency considerations, and practical model benchmarking.',
      },
      {
        id: 'les-1-2',
        title: 'Prompting & Content Generation',
        durationMinutes: 90,
        isFree: false,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b02',
        description: 'System prompts, few-shot examples, JSON schema enforcement, reasoning scaffolds, and anti-hallucination techniques.',
      },
      {
        id: 'les-1-3',
        title: 'Prompting Pt 2 — Structured Extraction & Chains',
        durationMinutes: 110,
        isFree: false,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b03',
        description: 'Extracting clean structured data from noisy PDF invoices, receipts, and multi-turn conversations.',
      },
    ],
  },
  {
    id: 'mod-2',
    number: 2,
    title: 'Automation with n8n',
    lessonCount: 2,
    totalDurationMinutes: 215,
    description: 'Orchestrating production workflows, webhooks, error handlers, and LLM nodes with self-hosted n8n.',
    lessons: [
      {
        id: 'les-2-1',
        title: 'Foundations of AI Automation & n8n',
        durationMinutes: 95,
        isFree: false,
        bunnyVideoId: '3c8901fe-5f72-4d22-9018-09acde330101',
        description: 'Deploying n8n instances, understanding webhook triggers, node data schemas, and credentials vaults.',
      },
      {
        id: 'les-2-2',
        title: 'AI-Powered Email Response System',
        durationMinutes: 120,
        isFree: false,
        bunnyVideoId: '3c8901fe-5f72-4d22-9018-09acde330102',
        description: 'End-to-end automated inbox manager with sentiment analysis, CRM lookup, draft generation, and human-in-the-loop approval.',
      },
    ],
  },
  {
    id: 'mod-3',
    number: 3,
    title: 'Building Autonomous AI Agents',
    lessonCount: 3,
    totalDurationMinutes: 340,
    description: 'State machines, function calling, tool execution, multi-agent coordination, and memory architectures.',
    lessons: [
      {
        id: 'les-3-1',
        title: 'Calendar Agent Pt 1 — Natural Language Scheduling',
        durationMinutes: 100,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990301',
        description: 'Constructing custom function calling schemas for Google Calendar API with timezone handling for West Africa (WAT).',
      },
      {
        id: 'les-3-2',
        title: 'Calendar Agent Pt 2 — Conflict Resolution & Multi-Party Invites',
        durationMinutes: 115,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990302',
        description: 'Handling edge cases, overlapping invite proposals, and resilient retry loops without infinite hallucination.',
      },
      {
        id: 'les-3-3',
        title: 'Agent Architectures, RAG & Context Engineering',
        durationMinutes: 125,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990303',
        description: 'Comparing ReAct, Plan-and-Solve, and LangGraph architectures. Managing sliding conversation memory cost-effectively.',
      },
    ],
  },
  {
    id: 'mod-4',
    number: 4,
    title: 'RAG in Practice — Production Retrieval',
    lessonCount: 2,
    totalDurationMinutes: 245,
    description: 'Vector embeddings, chunking strategies, hybrid search (BM25 + cosine), reranking, and enterprise document QA.',
    lessons: [
      {
        id: 'les-4-1',
        title: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
        durationMinutes: 115,
        isFree: false,
        bunnyVideoId: '5420ac88-99ee-471a-9cd4-325ea8290401',
        description: 'Parsing PDF contracts, semantic chunking boundaries, and pushing embeddings to Pinecone and pgvector.',
      },
      {
        id: 'les-4-2',
        title: 'RAG Agent & Pipeline Pt 2 — Retrieval, Reranking & Evaluation',
        durationMinutes: 130,
        isFree: false,
        bunnyVideoId: '5420ac88-99ee-471a-9cd4-325ea8290402',
        description: 'Implementing Cohere/BGE rerankers, contextual query rewrites, hallucination guards, and evaluation metrics.',
      },
    ],
  },
  {
    id: 'mod-5',
    number: 5,
    title: 'Shipping Commercial Products',
    lessonCount: 3,
    totalDurationMinutes: 325,
    description: 'Turning AI capabilities into customer-facing web applications, payment-gated SaaS, and vibe-coded prototypes.',
    lessons: [
      {
        id: 'les-5-1',
        title: 'Website & Chatbot with Lovable + n8n',
        durationMinutes: 105,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910501',
        description: 'Rapidly prototyping full-stack landing pages and dynamic conversational front-ends synced with n8n webhooks.',
      },
      {
        id: 'les-5-2',
        title: 'Vibe Coding Pt 1 — Rapid Prototyping & Architecture',
        durationMinutes: 100,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910502',
        description: 'Supercharging software development using modern AI coding agents, prompt specification files, and component scaffolding.',
      },
      {
        id: 'les-5-3',
        title: 'Vibe Coding Pt 2 — Production Hardening & Deployment',
        durationMinutes: 120,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910503',
        description: 'Taking prototype applications through TypeScript type safety, error boundaries, rate limiting, and global CDN deployment.',
      },
    ],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Chinedu Eze',
    role: 'Lead Backend Engineer',
    company: 'Fintech Startup, Lagos',
    initials: 'CE',
    quote:
      'Flag Skool demystified agents completely. I went from reading academic AI papers to deploying an automated customer reconciliations agent that saved our finance team 18 hours weekly.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Amina Bello',
    role: 'Technical Founder & Product Lead',
    company: 'Logistics Tech, Abuja',
    initials: 'AB',
    quote:
      'The n8n and RAG modules alone paid for the tuition ten times over. The focus on real Nigerian operational contexts, Nigerian phone/SMS webhooks, and cost-efficient token routing was unmatched.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Femi Ogundipe',
    role: 'Full-Stack Developer',
    company: 'Independent Contractor, Ibadan',
    initials: 'FO',
    quote:
      'I was able to close my first $3,500 international client contract for an automated email + calendar agent pipeline within two weeks of finishing Module 3. The code blueprints are gold.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
];

export const MOCK_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How long do I have access to the materials and recordings?',
    answer:
      'You receive permanent lifetime access to all purchased recordings, slides, n8n workflow blueprints, and GitHub repositories. You can revisit them anytime as you build in your career.',
    category: 'Access',
  },
  {
    id: 'faq-2',
    question: 'What payment methods are supported for Nigerian and international cards?',
    answer:
      'We accept all Nigerian debit cards (Mastercard, Visa, Verve), direct Nigerian bank transfers, USSD, and international card payments via secure instant checkout.',
    category: 'Billing',
  },
  {
    id: 'faq-3',
    question: 'How much internet data will I need to stream or download lessons?',
    answer:
      'All video sessions are hosted on an optimized high-speed global CDN with adaptive multi-bitrate streaming (360p, 720p, 1080p). Streaming a 90-minute session uses approximately 350MB–650MB depending on your selected resolution.',
    category: 'Technical',
  },
  {
    id: 'faq-4',
    question: 'What hardware or operating system do I need?',
    answer:
      'Any standard laptop or desktop computer (Windows, macOS, Linux) with at least 8GB of RAM. We also provide instructions for running browser-based cloud workspaces so you do not need an expensive GPU.',
    category: 'Requirements',
  },
  {
    id: 'faq-5',
    question: 'What is the refund policy if the program is not right for me?',
    answer:
      'We offer a 7-day money-back guarantee. If you review the first two modules, complete the onboarding setup, and feel Flag Skool is not delivering tremendous value, email support for a full refund.',
    category: 'Policy',
  },
  {
    id: 'faq-6',
    question: 'How does Live Cohort 2 differ from the On-Demand Recordings package?',
    answer:
      'The Recordings package gives you the full self-paced video archive and blueprints from Cohort 1. Live Cohort 2 adds 6 weeks of live weekend interactive sessions, live build-alongs, direct code reviews with Tobi, private VIP channel access, and capstone project certification.',
    category: 'Curriculum',
  },
];

export const MOCK_RESOURCES: VaultResource[] = [
  {
    id: 'res-1',
    title: 'n8n Production Calendar Agent Workflow (JSON Blueprint)',
    description: 'Complete multi-turn calendar agent workflow with WAT timezone conversions and conflict resolution nodes.',
    kind: 'blueprint',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-2',
    lessonTitle: 'Calendar Agent Pt 2 — Conflict Resolution & Multi-Party Invites',
    fileFormat: 'JSON',
    sizeFormatted: '48 KB',
    sizeBytes: 49152,
    downloadUrl: '#download-calendar-agent-json',
  },
  {
    id: 'res-2',
    title: 'AI-Powered Inbound Email Triage System (n8n JSON Blueprint)',
    description: 'Sentiment router, vector search similarity check, and draft generator with human-in-the-loop approval triggers.',
    kind: 'blueprint',
    moduleId: 'mod-2',
    moduleNumber: 2,
    moduleTitle: 'Automation with n8n',
    lessonId: 'les-2-2',
    lessonTitle: 'AI-Powered Email Response System',
    fileFormat: 'JSON',
    sizeFormatted: '62 KB',
    sizeBytes: 63488,
    downloadUrl: '#download-email-triage-json',
  },
  {
    id: 'res-3',
    title: 'Full-Stack Agent Backend Boilerplate (FastAPI + LangGraph)',
    description: 'Production-ready Python repository containing streaming SSE endpoints, PostgreSQL session memory, and tool contracts.',
    kind: 'code',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-3',
    lessonTitle: 'Agent Architectures, RAG & Context Engineering',
    fileFormat: 'ZIP',
    sizeFormatted: '2.4 MB',
    sizeBytes: 2516582,
    downloadUrl: '#download-fastapi-agent-zip',
  },
  {
    id: 'res-4',
    title: 'Enterprise RAG Ingestion & Hybrid Search Pipeline (Python/pgvector)',
    description: 'Clean ingestion scripts with semantic chunking, Cohere reranking, and BM25 hybrid ranking over local documents.',
    kind: 'code',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-1',
    lessonTitle: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
    fileFormat: 'ZIP',
    sizeFormatted: '1.8 MB',
    sizeBytes: 1887436,
    downloadUrl: '#download-rag-pipeline-zip',
  },
  {
    id: 'res-5',
    title: 'Masterclass Slide Deck: Autonomous Multi-Step Agents',
    description: 'High-resolution presentation deck covering state graphs, reflection loops, tool schemas, and cost optimization.',
    kind: 'slide',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-1',
    lessonTitle: 'Calendar Agent Pt 1 — Natural Language Scheduling',
    fileFormat: 'PDF',
    sizeFormatted: '14.2 MB',
    sizeBytes: 14889779,
    downloadUrl: '#download-module-3-slides-pdf',
  },
  {
    id: 'res-6',
    title: 'Masterclass Slide Deck: RAG, Chunking & Evaluation Benchmarks',
    description: 'Comprehensive guide to chunk sizing, embedding models, RAG Triad evaluations, and Nigerian compliance docs retrieval.',
    kind: 'slide',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-2',
    lessonTitle: 'RAG Agent & Pipeline Pt 2 — Retrieval, Reranking & Evaluation',
    fileFormat: 'PDF',
    sizeFormatted: '18.6 MB',
    sizeBytes: 19503513,
    downloadUrl: '#download-module-4-slides-pdf',
  },
  {
    id: 'res-7',
    title: 'Nigerian Regulatory & Financial Documents Corpus (Sample RAG Dataset)',
    description: 'Cleaned JSONL evaluation dataset containing 400+ indexed regulatory circulars and financial clauses for RAG testing.',
    kind: 'dataset',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-1',
    lessonTitle: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
    fileFormat: 'JSONL',
    sizeFormatted: '4.1 MB',
    sizeBytes: 4300000,
    downloadUrl: '#download-corpus-dataset-jsonl',
  },
  {
    id: 'res-8',
    title: 'Lovable Full-Stack AI Webapp Starter & Vibe Coding Prompt Guide',
    description: 'Pre-configured Tailwind + React front-end template with webhook connectors and step-by-step vibe coding prompts.',
    kind: 'code',
    moduleId: 'mod-5',
    moduleNumber: 5,
    moduleTitle: 'Shipping Commercial Products',
    lessonId: 'les-5-1',
    lessonTitle: 'Website & Chatbot with Lovable + n8n',
    fileFormat: 'ZIP',
    sizeFormatted: '3.6 MB',
    sizeBytes: 3774873,
    downloadUrl: '#download-lovable-starter-zip',
  },
  {
    id: 'res-9',
    title: 'AI Foundations & Prompt Architecture Cheat Sheet',
    description: 'Quick reference guide for system instructions, JSON schema constraints, reasoning tags, and few-shot formatting.',
    kind: 'doc',
    moduleId: 'mod-1',
    moduleNumber: 1,
    moduleTitle: 'AI Foundations & Engineering Mindset',
    lessonId: 'les-1-2',
    lessonTitle: 'Prompting & Content Generation',
    fileFormat: 'PDF',
    sizeFormatted: '2.1 MB',
    sizeBytes: 2202009,
    downloadUrl: '#download-prompting-cheatsheet-pdf',
  },
];

export const MOCK_COMMENTS: LessonComment[] = [
  {
    id: 'com-pin-1',
    lessonId: 'les-3-2',
    authorName: 'Tobi Adebayo',
    authorEmail: 'tobi@flagskool.com',
    authorIsAdmin: true,
    createdAt: '2 days ago',
    body: '📌 Key take-away: Always configure timezone fallbacks when dealing with WAT (UTC+1) in Google Calendar API. If a client sends "tomorrow at 3pm" from London, your function schema must explicitly preserve the sender\'s local offset before scheduling.',
    isPinned: true,
  },
  {
    id: 'com-2',
    lessonId: 'les-3-2',
    authorName: 'Emeka Nwosu',
    authorEmail: 'emeka.nwosu@gmail.com',
    authorIsAdmin: false,
    createdAt: '3 hours ago',
    body: 'The conflict resolution logic at 48:20 was super clear! I successfully tested this with my team\'s calendar in n8n and it resolved overlapping booking requests seamlessly.',
    isPinned: false,
  },
  {
    id: 'com-3',
    lessonId: 'les-3-2',
    authorName: 'Fatima Yusuf',
    authorEmail: 'fatima.yusuf@devmail.ng',
    authorIsAdmin: false,
    createdAt: '1 day ago',
    body: 'Question: If the invitee rejects the suggested reschedule slot twice, what is the best practice for stopping the agent from infinitely proposing new slots? Answered at 1:12:00 — max retry loop counter of 3.',
    isPinned: false,
  },
  {
    id: 'com-4',
    lessonId: 'les-1-1',
    authorName: 'Tobi Adebayo',
    authorEmail: 'tobi@flagskool.com',
    authorIsAdmin: true,
    createdAt: '1 week ago',
    body: '📌 Welcome everyone to Flag Skool! Make sure to clone the starter repo and verify your environment before moving on to Module 2.',
    isPinned: true,
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-4911',
  fullName: 'Chidi Okonkwo',
  email: 'chidi.okonkwo@gmail.com',
  avatarUrl: '',
  role: 'student',
  tier: 'cohort',
  joinedDate: 'February 2026',
};

export const MOCK_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-9081',
    tierId: 'cohort',
    tierName: 'Live Cohort 2 + Complete Archive',
    purchaseDate: 'February 18, 2026',
    amountPaidKobo: 10000000,
    status: 'active',
    reference: 'FLG-CHK-9812401',
  },
  {
    id: 'enr-9011',
    tierId: 'recordings',
    tierName: 'On-Demand Recordings Archive',
    purchaseDate: 'January 10, 2026',
    amountPaidKobo: 5000000,
    status: 'active',
    reference: 'FLG-CHK-8812309',
  },
];

export const MOCK_ADMIN_MODULES: AdminModule[] = MOCK_MODULES.map((m) => ({
  id: m.id,
  number: m.number,
  title: m.title,
  description: m.description,
  lessonCount: m.lessonCount,
  totalDurationMinutes: m.totalDurationMinutes,
  lessons: m.lessons.map((l) => ({
    ...l,
    isPublished: true,
    resources: MOCK_RESOURCES.filter((r) => r.lessonId === l.id),
  })),
}));

export const mockModules = MOCK_MODULES;
export const mockTestimonials = MOCK_TESTIMONIALS;
export const mockFaqs = MOCK_FAQS;
export const mockResources = MOCK_RESOURCES;
export const mockComments = MOCK_COMMENTS;
export const mockUserProfile = MOCK_USER_PROFILE;
export const mockEnrollments = MOCK_ENROLLMENTS;
