import {
  Module,
  Testimonial,
  FAQItem,
  VaultResource,
  LessonComment,
  UserProfile,
  Enrollment,
} from '@/types/index';

export const MOCK_MODULES: Module[] = [
  {
    id: 'mod-0',
    number: 0,
    title: 'Onboarding & Workspace Setup',
    lessonCount: 2,
    totalDurationMinutes: 85,
    description: 'Orientation, tools provisioning, development environments, and community protocols.',
    lessons: [
      {
        id: 'les-0-1',
        title: 'Platform Overview, Community Guidelines & Tool Stack',
        durationMinutes: 40,
        isFree: false,
        bunnyVideoId: 'f6b219a1-081b-411a-8c9e-2e4a81d11100',
        description: 'Introduction to our learning platform, Telegram workspace, API access keys, and project milestones.',
      },
      {
        id: 'les-0-2',
        title: 'Local Environment, Node.js, Python & Cloud Sandboxes',
        durationMinutes: 45,
        isFree: false,
        bunnyVideoId: 'f6b219a1-081b-411a-8c9e-2e4a81d11101',
        description: 'Setting up clean environments, secure token management, and containerized development tools.',
      },
    ],
  },
  {
    id: 'mod-1',
    number: 1,
    title: 'AI Foundations & Engineering Mindset',
    lessonCount: 3,
    totalDurationMinutes: 295,
    description: 'Deep dive into LLM mechanics, tokenization, context windows, and deterministic prompting techniques.',
    lessons: [
      {
        id: 'les-1-1',
        title: 'Fundamentals of AI',
        durationMinutes: 95,
        isFree: true,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b01',
        description: 'How modern transformer models think, embeddings, temperature, latency considerations, and practical model benchmarking.',
      },
      {
        id: 'les-1-2',
        title: 'Prompting & Content Generation',
        durationMinutes: 90,
        isFree: false,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b02',
        description: 'System prompts, few-shot examples, JSON schema enforcement, reasoning scaffolds, and anti-hallucination techniques.',
      },
      {
        id: 'les-1-3',
        title: 'Prompting Pt 2 — Structured Extraction & Chains',
        durationMinutes: 110,
        isFree: false,
        bunnyVideoId: '7a119bc2-31fa-4f90-84cf-ea8547c94b03',
        description: 'Extracting clean structured data from noisy PDF invoices, receipts, and multi-turn conversations.',
      },
    ],
  },
  {
    id: 'mod-2',
    number: 2,
    title: 'Automation with n8n',
    lessonCount: 2,
    totalDurationMinutes: 215,
    description: 'Orchestrating production workflows, webhooks, error handlers, and LLM nodes with self-hosted n8n.',
    lessons: [
      {
        id: 'les-2-1',
        title: 'Foundations of AI Automation & n8n',
        durationMinutes: 95,
        isFree: false,
        bunnyVideoId: '3c8901fe-5f72-4d22-9018-09acde330101',
        description: 'Deploying n8n instances, understanding webhook triggers, node data schemas, and credentials vaults.',
      },
      {
        id: 'les-2-2',
        title: 'AI-Powered Email Response System',
        durationMinutes: 120,
        isFree: false,
        bunnyVideoId: '3c8901fe-5f72-4d22-9018-09acde330102',
        description: 'End-to-end automated inbox manager with sentiment analysis, CRM lookup, draft generation, and human-in-the-loop approval.',
      },
    ],
  },
  {
    id: 'mod-3',
    number: 3,
    title: 'Building Autonomous AI Agents',
    lessonCount: 3,
    totalDurationMinutes: 340,
    description: 'State machines, function calling, tool execution, multi-agent coordination, and memory architectures.',
    lessons: [
      {
        id: 'les-3-1',
        title: 'Calendar Agent Pt 1 — Natural Language Scheduling',
        durationMinutes: 100,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990301',
        description: 'Constructing custom function calling schemas for Google Calendar API with timezone handling for West Africa (WAT).',
      },
      {
        id: 'les-3-2',
        title: 'Calendar Agent Pt 2 — Conflict Resolution & Multi-Party Invites',
        durationMinutes: 115,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990302',
        description: 'Handling edge cases, overlapping invite proposals, and resilient retry loops without infinite hallucination.',
      },
      {
        id: 'les-3-3',
        title: 'Agent Architectures, RAG & Context Engineering',
        durationMinutes: 125,
        isFree: false,
        bunnyVideoId: '98d5c412-11ae-4cb8-bdf2-f8c6e3990303',
        description: 'Comparing ReAct, Plan-and-Solve, and LangGraph architectures. Managing sliding conversation memory cost-effectively.',
      },
    ],
  },
  {
    id: 'mod-4',
    number: 4,
    title: 'RAG in Practice — Production Retrieval',
    lessonCount: 2,
    totalDurationMinutes: 245,
    description: 'Vector embeddings, chunking strategies, hybrid search (BM25 + cosine), reranking, and enterprise document QA.',
    lessons: [
      {
        id: 'les-4-1',
        title: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
        durationMinutes: 115,
        isFree: false,
        bunnyVideoId: '5420ac88-99ee-471a-9cd4-325ea8290401',
        description: 'Parsing PDF contracts, semantic chunking boundaries, and pushing embeddings to Pinecone and pgvector.',
      },
      {
        id: 'les-4-2',
        title: 'RAG Agent & Pipeline Pt 2 — Retrieval, Reranking & Evaluation',
        durationMinutes: 130,
        isFree: false,
        bunnyVideoId: '5420ac88-99ee-471a-9cd4-325ea8290402',
        description: 'Implementing Cohere/BGE rerankers, contextual query rewrites, hallucination guards, and evaluation metrics.',
      },
    ],
  },
  {
    id: 'mod-5',
    number: 5,
    title: 'Shipping Commercial Products',
    lessonCount: 3,
    totalDurationMinutes: 325,
    description: 'Turning AI capabilities into customer-facing web applications, payment-gated SaaS, and vibe-coded prototypes.',
    lessons: [
      {
        id: 'les-5-1',
        title: 'Website & Chatbot with Lovable + n8n',
        durationMinutes: 105,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910501',
        description: 'Rapidly prototyping full-stack landing pages and dynamic conversational front-ends synced with n8n webhooks.',
      },
      {
        id: 'les-5-2',
        title: 'Vibe Coding Pt 1 — Rapid Prototyping & Architecture',
        durationMinutes: 100,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910502',
        description: 'Supercharging software development using modern AI coding agents, prompt specification files, and component scaffolding.',
      },
      {
        id: 'les-5-3',
        title: 'Vibe Coding Pt 2 — Production Hardening & Deployment',
        durationMinutes: 120,
        isFree: false,
        bunnyVideoId: '1a980dd3-7621-4f55-88ab-f05cb2910503',
        description: 'Taking prototype applications through TypeScript type safety, error boundaries, rate limiting, and global CDN deployment.',
      },
    ],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Chinedu Eze',
    role: 'Lead Backend Engineer',
    company: 'Fintech Startup, Lagos',
    initials: 'CE',
    quote:
      'Flag Skool demystified agents completely. I went from reading academic AI papers to deploying an automated customer reconciliations agent that saved our finance team 18 hours weekly.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Amina Bello',
    role: 'Technical Founder & Product Lead',
    company: 'Logistics Tech, Abuja',
    initials: 'AB',
    quote:
      'The n8n and RAG modules alone paid for the tuition ten times over. The focus on real Nigerian operational contexts, Nigerian phone/SMS webhooks, and cost-efficient token routing was unmatched.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Femi Ogundipe',
    role: 'Full-Stack Developer',
    company: 'Independent Contractor, Ibadan',
    initials: 'FO',
    quote:
      'I was able to close my first $3,500 international client contract for an automated email + calendar agent pipeline within two weeks of finishing Module 3. The code blueprints are gold.',
    cohort: 'Cohort 1 Alum',
    rating: 5,
  },
];

export const MOCK_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How long do I have access to the materials and recordings?',
    answer:
      'You receive permanent lifetime access to all purchased recordings, slides, n8n workflow blueprints, and GitHub repositories. You can revisit them anytime as you build in your career.',
    category: 'Access',
  },
  {
    id: 'faq-2',
    question: 'What payment methods are supported for Nigerian and international cards?',
    answer:
      'We accept all Nigerian debit cards (Mastercard, Visa, Verve), direct Nigerian bank transfers, USSD, and international card payments via secure instant checkout.',
    category: 'Billing',
  },
  {
    id: 'faq-3',
    question: 'How much internet data will I need to stream or download lessons?',
    answer:
      'All video sessions are hosted on an optimized high-speed global CDN with adaptive multi-bitrate streaming (360p, 720p, 1080p). Streaming a 90-minute session uses approximately 350MB–650MB depending on your selected resolution.',
    category: 'Technical',
  },
  {
    id: 'faq-4',
    question: 'What hardware or operating system do I need?',
    answer:
      'Any standard laptop or desktop computer (Windows, macOS, Linux) with at least 8GB of RAM. We also provide instructions for running browser-based cloud workspaces so you do not need an expensive GPU.',
    category: 'Requirements',
  },
  {
    id: 'faq-5',
    question: 'What is the refund policy if the program is not right for me?',
    answer:
      'We offer a 7-day money-back guarantee. If you review the first two modules, complete the onboarding setup, and feel Flag Skool is not delivering tremendous value, email support for a full refund.',
    category: 'Policy',
  },
  {
    id: 'faq-6',
    question: 'How does Live Cohort 2 differ from the On-Demand Recordings package?',
    answer:
      'The Recordings package gives you the full self-paced video archive and blueprints from Cohort 1. Live Cohort 2 adds 6 weeks of live weekend interactive sessions, live build-alongs, direct code reviews with Tobi, private VIP channel access, and capstone project certification.',
    category: 'Curriculum',
  },
];

export const MOCK_RESOURCES: VaultResource[] = [
  {
    id: 'res-1',
    title: 'n8n Production Calendar Agent Workflow (JSON Blueprint)',
    description: 'Complete multi-turn calendar agent workflow with WAT timezone conversions and conflict resolution nodes.',
    kind: 'blueprint',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-2',
    lessonTitle: 'Calendar Agent Pt 2 — Conflict Resolution & Multi-Party Invites',
    fileFormat: 'JSON',
    sizeFormatted: '48 KB',
    sizeBytes: 49152,
    downloadUrl: '#download-calendar-agent-json',
  },
  {
    id: 'res-2',
    title: 'AI-Powered Inbound Email Triage System (n8n JSON Blueprint)',
    description: 'Sentiment router, vector search similarity check, and draft generator with human-in-the-loop approval triggers.',
    kind: 'blueprint',
    moduleId: 'mod-2',
    moduleNumber: 2,
    moduleTitle: 'Automation with n8n',
    lessonId: 'les-2-2',
    lessonTitle: 'AI-Powered Email Response System',
    fileFormat: 'JSON',
    sizeFormatted: '62 KB',
    sizeBytes: 63488,
    downloadUrl: '#download-email-triage-json',
  },
  {
    id: 'res-3',
    title: 'Full-Stack Agent Backend Boilerplate (FastAPI + LangGraph)',
    description: 'Production-ready Python repository containing streaming SSE endpoints, PostgreSQL session memory, and tool contracts.',
    kind: 'code',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-3',
    lessonTitle: 'Agent Architectures, RAG & Context Engineering',
    fileFormat: 'ZIP',
    sizeFormatted: '2.4 MB',
    sizeBytes: 2516582,
    downloadUrl: '#download-fastapi-agent-zip',
  },
  {
    id: 'res-4',
    title: 'Enterprise RAG Ingestion & Hybrid Search Pipeline (Python/pgvector)',
    description: 'Clean ingestion scripts with semantic chunking, Cohere reranking, and BM25 hybrid ranking over local documents.',
    kind: 'code',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-1',
    lessonTitle: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
    fileFormat: 'ZIP',
    sizeFormatted: '1.8 MB',
    sizeBytes: 1887436,
    downloadUrl: '#download-rag-pipeline-zip',
  },
  {
    id: 'res-5',
    title: 'Masterclass Slide Deck: Autonomous Multi-Step Agents',
    description: 'High-resolution presentation deck covering state graphs, reflection loops, tool schemas, and cost optimization.',
    kind: 'slide',
    moduleId: 'mod-3',
    moduleNumber: 3,
    moduleTitle: 'Building Autonomous AI Agents',
    lessonId: 'les-3-1',
    lessonTitle: 'Calendar Agent Pt 1 — Natural Language Scheduling',
    fileFormat: 'PDF',
    sizeFormatted: '14.2 MB',
    sizeBytes: 14889779,
    downloadUrl: '#download-module-3-slides-pdf',
  },
  {
    id: 'res-6',
    title: 'Masterclass Slide Deck: RAG, Chunking & Evaluation Benchmarks',
    description: 'Comprehensive guide to chunk sizing, embedding models, RAG Triad evaluations, and Nigerian compliance docs retrieval.',
    kind: 'slide',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-2',
    lessonTitle: 'RAG Agent & Pipeline Pt 2 — Retrieval, Reranking & Evaluation',
    fileFormat: 'PDF',
    sizeFormatted: '18.6 MB',
    sizeBytes: 19503513,
    downloadUrl: '#download-module-4-slides-pdf',
  },
  {
    id: 'res-7',
    title: 'Nigerian Regulatory & Financial Documents Corpus (Sample RAG Dataset)',
    description: 'Cleaned JSONL evaluation dataset containing 400+ indexed regulatory circulars and financial clauses for RAG testing.',
    kind: 'dataset',
    moduleId: 'mod-4',
    moduleNumber: 4,
    moduleTitle: 'RAG in Practice — Production Retrieval',
    lessonId: 'les-4-1',
    lessonTitle: 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking',
    fileFormat: 'JSONL',
    sizeFormatted: '4.1 MB',
    sizeBytes: 4300000,
    downloadUrl: '#download-corpus-dataset-jsonl',
  },
  {
    id: 'res-8',
    title: 'Lovable Full-Stack AI Webapp Starter & Vibe Coding Prompt Guide',
    description: 'Pre-configured Tailwind + React front-end template with webhook connectors and step-by-step vibe coding prompts.',
    kind: 'code',
    moduleId: 'mod-5',
    moduleNumber: 5,
    moduleTitle: 'Shipping Commercial Products',
    lessonId: 'les-5-1',
    lessonTitle: 'Website & Chatbot with Lovable + n8n',
    fileFormat: 'ZIP',
    sizeFormatted: '3.6 MB',
    sizeBytes: 3774873,
    downloadUrl: '#download-lovable-starter-zip',
  },
  {
    id: 'res-9',
    title: 'AI Foundations & Prompt Architecture Cheat Sheet',
    description: 'Quick reference guide for system instructions, JSON schema constraints, reasoning tags, and few-shot formatting.',
    kind: 'doc',
    moduleId: 'mod-1',
    moduleNumber: 1,
    moduleTitle: 'AI Foundations & Engineering Mindset',
    lessonId: 'les-1-2',
    lessonTitle: 'Prompting & Content Generation',
    fileFormat: 'PDF',
    sizeFormatted: '2.1 MB',
    sizeBytes: 2202009,
    downloadUrl: '#download-prompting-cheatsheet-pdf',
  },
];

export const MOCK_COMMENTS: LessonComment[] = [
  {
    id: 'com-pin-1',
    lessonId: 'les-3-2',
    authorName: 'Tobi Adebayo',
    authorEmail: 'tobi@flagskool.com',
    authorIsAdmin: true,
    createdAt: '2 days ago',
    body: '📌 Key take-away: Always configure timezone fallbacks when dealing with WAT (UTC+1) in Google Calendar API. If a client sends "tomorrow at 3pm" from London, your function schema must explicitly preserve the sender\'s local offset before scheduling.',
    isPinned: true,
  },
  {
    id: 'com-2',
    lessonId: 'les-3-2',
    authorName: 'Emeka Nwosu',
    authorEmail: 'emeka.nwosu@gmail.com',
    authorIsAdmin: false,
    createdAt: '3 hours ago',
    body: 'The conflict resolution logic at 48:20 was super clear! I successfully tested this with my team\'s calendar in n8n and it resolved overlapping booking requests seamlessly.',
    isPinned: false,
  },
  {
    id: 'com-3',
    lessonId: 'les-3-2',
    authorName: 'Fatima Yusuf',
    authorEmail: 'fatima.yusuf@devmail.ng',
    authorIsAdmin: false,
    createdAt: '1 day ago',
    body: 'Question: If the invitee rejects the suggested reschedule slot twice, what is the best practice for stopping the agent from infinitely proposing new slots? Answered at 1:12:00 — max retry loop counter of 3.',
    isPinned: false,
  },
  {
    id: 'com-4',
    lessonId: 'les-1-1',
    authorName: 'Tobi Adebayo',
    authorEmail: 'tobi@flagskool.com',
    authorIsAdmin: true,
    createdAt: '1 week ago',
    body: '📌 Welcome everyone to Flag Skool! Make sure to clone the starter repo and verify your environment before moving on to Module 2.',
    isPinned: true,
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-4911',
  fullName: 'Chidi Okonkwo',
  email: 'chidi.okonkwo@gmail.com',
  avatarUrl: '',
  role: 'student',
  tier: 'cohort',
  joinedDate: 'February 2026',
};

export const MOCK_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-9081',
    tierId: 'cohort',
    tierName: 'Live Cohort 2 + Complete Archive',
    purchaseDate: 'February 18, 2026',
    amountPaidNgn: 100000,
    status: 'active',
    reference: 'FLG-CHK-9812401',
  },
  {
    id: 'enr-9011',
    tierId: 'recordings',
    tierName: 'On-Demand Recordings Archive',
    purchaseDate: 'January 10, 2026',
    amountPaidNgn: 50000,
    status: 'active',
    reference: 'FLG-CHK-8812309',
  },
];

export const mockModules = MOCK_MODULES;
export const mockTestimonials = MOCK_TESTIMONIALS;
export const mockFaqs = MOCK_FAQS;
export const mockResources = MOCK_RESOURCES;
export const mockComments = MOCK_COMMENTS;
export const mockUserProfile = MOCK_USER_PROFILE;
export const mockEnrollments = MOCK_ENROLLMENTS;
