-- =============================================================================
-- Flag Skool — curriculum seed
--
-- GENERATED by scripts/generate-seed-sql.mjs from lib/mock-data.ts.
-- Do not hand-edit; change the source data and regenerate.
--
-- Idempotent and safe to re-run against production: every insert is ON
-- CONFLICT DO NOTHING against a natural key, and ids are deterministic
-- UUIDv5 values derived from the content slugs.
--
-- This is fixed course content, which is why it lives in a migration rather
-- than a seed script. Test students and fake transactions do NOT belong here
-- — those live in scripts/seed-test-data.ts.
-- =============================================================================

-- organization -----------------------------------------------------------------
insert into public.organizations (id, slug, name) values
  ('6cf541c4-f870-5858-a49c-3b2de28ba050', 'flag-skool', 'Flag Skool')
on conflict (slug) do nothing;

-- products ---------------------------------------------------------------------
-- Prices mirror config/flagskool.config.ts, in kobo. A cohort purchase grants
-- the recordings sku as well; that is what products.grants_skus is for.
insert into public.products (id, org_id, sku, title, subtitle, price_kobo, grants_skus) values
  ('8c37c0a4-7d43-5397-9736-2cda16b7939e', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 'On-Demand Recordings', 'Self-Paced', 10000000, '{}'),
  ('d5c83db8-74a0-558f-bc85-5b229c6ac727', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'cohort', 'Live Cohort 2 + Complete Archive', 'Most Recommended', 15000000, '{recordings}')
on conflict (org_id, sku) do nothing;

-- modules ----------------------------------------------------------------------
insert into public.modules (id, org_id, product_sku, order_index, title, description) values
  ('5e7c67b5-e24d-5478-9bbd-b8920f1fb92d', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 0, 'Onboarding & Workspace Setup', 'Orientation, tools provisioning, development environments, and community protocols.'),
  ('1c4d32ba-20e8-5dd6-ac61-ef0f1b98313e', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 1, 'AI Foundations & Engineering Mindset', 'Deep dive into LLM mechanics, tokenization, context windows, and deterministic prompting techniques.'),
  ('1fbf40f2-7546-5b34-8ffd-324654424151', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 2, 'Automation with n8n', 'Orchestrating production workflows, webhooks, error handlers, and LLM nodes with self-hosted n8n.'),
  ('65d832f1-11ca-52d3-88dc-3a6991b8d4c8', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 3, 'Building Autonomous AI Agents', 'State machines, function calling, tool execution, multi-agent coordination, and memory architectures.'),
  ('97142077-2f69-5e30-8e44-237aca830dc7', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'recordings', 4, 'RAG in Practice — Production Retrieval', 'Vector embeddings, chunking strategies, hybrid search (BM25 + cosine), reranking, and enterprise document QA.'),
  ('6852ca4e-8d7c-51b2-8161-1d9124728665', '6cf541c4-f870-5858-a49c-3b2de28ba050', 'cohort', 5, 'Shipping Commercial Products', 'Turning AI capabilities into customer-facing web applications, payment-gated SaaS, and vibe-coded prototypes.')
on conflict (org_id, order_index) do nothing;

-- lessons ----------------------------------------------------------------------
-- bunny_video_id values are the AI Studio placeholders. They are replaced with
-- real Bunny Stream ids in Stage 2; playback is signed server-side either way.
-- published_at is set so the curriculum is visible; entitlement is what gates
-- access, not publication.
insert into public.lessons (id, org_id, module_id, order_index, title, description, bunny_video_id, duration_seconds, is_free_preview, published_at) values
  ('425d9a46-75c8-57df-a1c0-38c152eb8ed1', '6cf541c4-f870-5858-a49c-3b2de28ba050', '5e7c67b5-e24d-5478-9bbd-b8920f1fb92d', 1, 'Platform Overview, Community Guidelines & Tool Stack', 'Introduction to our learning platform, Telegram workspace, API access keys, and project milestones.', 'f6b219a1-081b-411a-8c9e-2e4a81d11100', 2400, false, now()),
  ('00d1632d-aa3c-5b88-942a-6717c608d55c', '6cf541c4-f870-5858-a49c-3b2de28ba050', '5e7c67b5-e24d-5478-9bbd-b8920f1fb92d', 2, 'Local Environment, Node.js, Python & Cloud Sandboxes', 'Setting up clean environments, secure token management, and containerized development tools.', 'f6b219a1-081b-411a-8c9e-2e4a81d11101', 2700, false, now()),
  ('13048d6a-a4f2-52c3-8c28-1cba977feed4', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1c4d32ba-20e8-5dd6-ac61-ef0f1b98313e', 1, 'Fundamentals of AI', 'How modern transformer models think, embeddings, temperature, latency considerations, and practical model benchmarking.', '7a119bc2-31fa-4f90-84cf-ea8547c94b01', 5700, true, now()),
  ('73779c06-cb8a-5c13-8a93-80028f446285', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1c4d32ba-20e8-5dd6-ac61-ef0f1b98313e', 2, 'Prompting & Content Generation', 'System prompts, few-shot examples, JSON schema enforcement, reasoning scaffolds, and anti-hallucination techniques.', '7a119bc2-31fa-4f90-84cf-ea8547c94b02', 5400, false, now()),
  ('959a58bf-6496-5d4c-96f0-363ee25694d5', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1c4d32ba-20e8-5dd6-ac61-ef0f1b98313e', 3, 'Prompting Pt 2 — Structured Extraction & Chains', 'Extracting clean structured data from noisy PDF invoices, receipts, and multi-turn conversations.', '7a119bc2-31fa-4f90-84cf-ea8547c94b03', 6600, false, now()),
  ('58cf56ff-8250-5fcc-9fab-2d4e97f27fee', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1fbf40f2-7546-5b34-8ffd-324654424151', 1, 'Foundations of AI Automation & n8n', 'Deploying n8n instances, understanding webhook triggers, node data schemas, and credentials vaults.', '3c8901fe-5f72-4d22-9018-09acde330101', 5700, false, now()),
  ('03434da3-a946-5919-ac84-2f9e8f2c82bc', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1fbf40f2-7546-5b34-8ffd-324654424151', 2, 'AI-Powered Email Response System', 'End-to-end automated inbox manager with sentiment analysis, CRM lookup, draft generation, and human-in-the-loop approval.', '3c8901fe-5f72-4d22-9018-09acde330102', 7200, false, now()),
  ('1e3ddbef-df6b-55b8-9b86-defd67de1853', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', 1, 'Calendar Agent Pt 1 — Natural Language Scheduling', 'Constructing custom function calling schemas for Google Calendar API with timezone handling for West Africa (WAT).', '98d5c412-11ae-4cb8-bdf2-f8c6e3990301', 6000, false, now()),
  ('e2ff48ab-2502-59e8-bb8a-f340ac3dd33a', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', 2, 'Calendar Agent Pt 2 — Conflict Resolution & Multi-Party Invites', 'Handling edge cases, overlapping invite proposals, and resilient retry loops without infinite hallucination.', '98d5c412-11ae-4cb8-bdf2-f8c6e3990302', 6900, false, now()),
  ('489318b9-ab81-55b7-b554-9df3f8a3ea01', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', 3, 'Agent Architectures, RAG & Context Engineering', 'Comparing ReAct, Plan-and-Solve, and LangGraph architectures. Managing sliding conversation memory cost-effectively.', '98d5c412-11ae-4cb8-bdf2-f8c6e3990303', 7500, false, now()),
  ('458d0623-f783-5fbc-b73e-01e5dbfd3b09', '6cf541c4-f870-5858-a49c-3b2de28ba050', '97142077-2f69-5e30-8e44-237aca830dc7', 1, 'RAG Agent & Pipeline Pt 1 — Ingestion & Chunking', 'Parsing PDF contracts, semantic chunking boundaries, and pushing embeddings to Pinecone and pgvector.', '5420ac88-99ee-471a-9cd4-325ea8290401', 6900, false, now()),
  ('9eca3c55-beb8-54f1-8079-22cc451f1d83', '6cf541c4-f870-5858-a49c-3b2de28ba050', '97142077-2f69-5e30-8e44-237aca830dc7', 2, 'RAG Agent & Pipeline Pt 2 — Retrieval, Reranking & Evaluation', 'Implementing Cohere/BGE rerankers, contextual query rewrites, hallucination guards, and evaluation metrics.', '5420ac88-99ee-471a-9cd4-325ea8290402', 7800, false, now()),
  ('5eda76ad-e0a7-53d4-acf7-a9f5625bad53', '6cf541c4-f870-5858-a49c-3b2de28ba050', '6852ca4e-8d7c-51b2-8161-1d9124728665', 1, 'Website & Chatbot with Lovable + n8n', 'Rapidly prototyping full-stack landing pages and dynamic conversational front-ends synced with n8n webhooks.', '1a980dd3-7621-4f55-88ab-f05cb2910501', 6300, false, now()),
  ('ba7c597c-ee6d-51a5-9bf5-c9302133866c', '6cf541c4-f870-5858-a49c-3b2de28ba050', '6852ca4e-8d7c-51b2-8161-1d9124728665', 2, 'Vibe Coding Pt 1 — Rapid Prototyping & Architecture', 'Supercharging software development using modern AI coding agents, prompt specification files, and component scaffolding.', '1a980dd3-7621-4f55-88ab-f05cb2910502', 6000, false, now()),
  ('3ee28147-6e94-5e3e-9dc4-4ddbd0bba1f8', '6cf541c4-f870-5858-a49c-3b2de28ba050', '6852ca4e-8d7c-51b2-8161-1d9124728665', 3, 'Vibe Coding Pt 2 — Production Hardening & Deployment', 'Taking prototype applications through TypeScript type safety, error boundaries, rate limiting, and global CDN deployment.', '1a980dd3-7621-4f55-88ab-f05cb2910503', 7200, false, now())
on conflict (module_id, order_index) do nothing;

-- resources --------------------------------------------------------------------
insert into public.resources (id, org_id, module_id, lesson_id, title, description, kind, file_format, storage_path, size_bytes) values
  ('dcc53d6a-d2e1-537c-824e-79ba3e5d3e4d', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', 'e2ff48ab-2502-59e8-bb8a-f340ac3dd33a', 'n8n Production Calendar Agent Workflow (JSON Blueprint)', 'Complete multi-turn calendar agent workflow with WAT timezone conversions and conflict resolution nodes.', 'blueprint', 'JSON', 'resources/res-1.json', 49152),
  ('2837e857-d82e-57e0-9d0f-265404df2e6e', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1fbf40f2-7546-5b34-8ffd-324654424151', '03434da3-a946-5919-ac84-2f9e8f2c82bc', 'AI-Powered Inbound Email Triage System (n8n JSON Blueprint)', 'Sentiment router, vector search similarity check, and draft generator with human-in-the-loop approval triggers.', 'blueprint', 'JSON', 'resources/res-2.json', 63488),
  ('5f49bd03-55e5-55dd-a340-049868926599', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', '489318b9-ab81-55b7-b554-9df3f8a3ea01', 'Full-Stack Agent Backend Boilerplate (FastAPI + LangGraph)', 'Production-ready Python repository containing streaming SSE endpoints, PostgreSQL session memory, and tool contracts.', 'code', 'ZIP', 'resources/res-3.zip', 2516582),
  ('51fb2da9-aa34-5211-b071-df03a23b318f', '6cf541c4-f870-5858-a49c-3b2de28ba050', '97142077-2f69-5e30-8e44-237aca830dc7', '458d0623-f783-5fbc-b73e-01e5dbfd3b09', 'Enterprise RAG Ingestion & Hybrid Search Pipeline (Python/pgvector)', 'Clean ingestion scripts with semantic chunking, Cohere reranking, and BM25 hybrid ranking over local documents.', 'code', 'ZIP', 'resources/res-4.zip', 1887436),
  ('6d659282-c49f-57b8-aa59-83ba641a61ec', '6cf541c4-f870-5858-a49c-3b2de28ba050', '65d832f1-11ca-52d3-88dc-3a6991b8d4c8', '1e3ddbef-df6b-55b8-9b86-defd67de1853', 'Masterclass Slide Deck: Autonomous Multi-Step Agents', 'High-resolution presentation deck covering state graphs, reflection loops, tool schemas, and cost optimization.', 'slide', 'PDF', 'resources/res-5.pdf', 14889779),
  ('d54cc7a0-67b6-55b6-9cab-dff1ccb71ef2', '6cf541c4-f870-5858-a49c-3b2de28ba050', '97142077-2f69-5e30-8e44-237aca830dc7', '9eca3c55-beb8-54f1-8079-22cc451f1d83', 'Masterclass Slide Deck: RAG, Chunking & Evaluation Benchmarks', 'Comprehensive guide to chunk sizing, embedding models, RAG Triad evaluations, and Nigerian compliance docs retrieval.', 'slide', 'PDF', 'resources/res-6.pdf', 19503513),
  ('a73559ef-ae1b-5d40-93dd-0504331d0e00', '6cf541c4-f870-5858-a49c-3b2de28ba050', '97142077-2f69-5e30-8e44-237aca830dc7', '458d0623-f783-5fbc-b73e-01e5dbfd3b09', 'Nigerian Regulatory & Financial Documents Corpus (Sample RAG Dataset)', 'Cleaned JSONL evaluation dataset containing 400+ indexed regulatory circulars and financial clauses for RAG testing.', 'dataset', 'JSONL', 'resources/res-7.jsonl', 4300000),
  ('a042759e-d72b-5451-9359-641781234075', '6cf541c4-f870-5858-a49c-3b2de28ba050', '6852ca4e-8d7c-51b2-8161-1d9124728665', '5eda76ad-e0a7-53d4-acf7-a9f5625bad53', 'Lovable Full-Stack AI Webapp Starter & Vibe Coding Prompt Guide', 'Pre-configured Tailwind + React front-end template with webhook connectors and step-by-step vibe coding prompts.', 'code', 'ZIP', 'resources/res-8.zip', 3774873),
  ('bd8cf9f1-0a45-5d87-83f8-07dee828a154', '6cf541c4-f870-5858-a49c-3b2de28ba050', '1c4d32ba-20e8-5dd6-ac61-ef0f1b98313e', '73779c06-cb8a-5c13-8a93-80028f446285', 'AI Foundations & Prompt Architecture Cheat Sheet', 'Quick reference guide for system instructions, JSON schema constraints, reasoning tags, and few-shot formatting.', 'doc', 'PDF', 'resources/res-9.pdf', 2202009)
on conflict (id) do nothing;
